### ISSUE TITLE
Enable the use of !stack_output for stack_config role_arn

### ISSUE THREAD

**Issue by schlichtanders** [Sceptre/sceptre#886] opened 2020-03-20 07:33 UTC
Dear sceptre team,

I am currently in the process of deploying EKS with sceptre and it turns out that AWS EKS cloudformation has the specificality that only the ARN which created the cluster can also change it.

Hence this is a case for sceptre's stack_config ``role_arn``. However the ``role_arn`` is defined within another stack, hence the intuitive thing todo would be
```
# my config.yaml for the stack create-eks-cluster.yaml
template_path: create-eks-cluster.yaml
role_arn: !stack_output create-role-arn.yaml::RoleArn
```

However this gives the following error:
```
Parameter validation failed:\nInvalid type for parameter RoleARN, value: <sceptre.resolvers.stack_output.StackOutput object at 0x7fc4183a99d0>, type: <class 'sceptre.resolvers.stack_output.StackOutput'>, valid types: <class 'str'>
```
which indicates that !stack_output is not  supported currently for ``role_arn`` (but only for ``parameters:`` I guess)

**Comment by craighurley** [comment] 2020-03-20 07:49
Resolvers (e.g. stack_output) only work in [Stack Config files](https://sceptre.cloudreach.com/2.3.0/docs/stack_config.html).  I believe you are trying to use a resolver in a [StackGroup Config file](https://sceptre.cloudreach.com/2.3.0/docs/stack_group_config.html).

**Comment by craighurley** [comment] 2020-03-20 07:54
_I deleted my previous comment as my response was incorrect._

From the [Resolvers](https://sceptre.cloudreach.com/2.3.0/docs/resolvers.html) doc:

> Sceptre implements resolvers, which can be used to resolve a value of a CloudFormation parameter or sceptre_user_data value at runtime. 

i.e. not for `role_arn`, although, it would be useful especially in your case.

**Comment by schlichtanders** [comment] 2020-03-20 08:54
I made a minimal implementation, missing tests and everything
I really don't know whether I can find the time to add the rest for a full pull-request,
I hope that even if not, this implementation would help someone else to complete the pull-request

(the implementation is working for me)

**Comment by schlichtanders** [comment] 2020-03-20 14:16
just checked ``iam_role`` because it apparently is quite similar.

Unfortunately the required amount of code-changes are much larger, because ``iam_role`` triggers the creation of a ``ResolveLater`` which seems really hard right now to support plain non-dict, non-list arguments. Maybe the ResolveLater logic would be good to review if ``iam_role`` should also be supported.

Luckily `role_arn` works super fine, and does not trigger any ResolveLater at all.

**Comment by schlichtanders** [comment] 2020-04-09 11:13
it would also be great to be able to use `!stack_output` in sceptre hooks

**Comment by zaro0508** [comment] 2021-12-05 00:51
I believe @jfalkenstein is implementing this in PR #1154

**Comment by zaro0508** [comment] 2021-12-05 00:52
closing as a duplicate of issue #1114

**Closed by zaro0508** 2021-12-05 00:52 UTC
Labels: type: feature request
