### ISSUE TITLE
Python 3.9 not supported

### ISSUE THREAD

**Issue by fxcoudert** [Sceptre/sceptre#942] opened 2020-10-07 23:31 UTC
```
  File "/usr/local/Cellar/sceptre/2.4.0_1/libexec/lib/python3.9/site-packages/networkx/algorithms/dag.py", line 23, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/fractions.py)
```

The networkx version specified is too old and does not support Python 3.9. fractions.gcd was removed.

**Comment by armanos** [comment] 2020-11-11 19:16
Ran into this exact problem today and was about to open a new issue. Would be really good to see this get fixed, since `gcd` has been deprecated since python 3.5 https://docs.python.org/3.5/library/fractions.html#fractions.gcd - the fix, as suggested in the official python documentation is to use `math.gcd()`

**Comment by armanos** [comment] 2020-11-11 19:28
Aha! `Networkx` has fixed this, but the issue is that Sceptre has this:
```
sceptre 2.4.0 requires networkx==2.1, but you'll have networkx 2.5 which is incompatible.
```

**Comment by armanos** [comment] 2020-11-11 19:31
Seems that these 3 files need to be updated and then tested:
- sceptre-repo/requirements/dev.txt:networkx==2.1
- sceptre-repo/requirements/prod.txt:networkx==2.1
- sceptre-repo/setup.py:    "networkx==2.1",

**Comment by jerry153fish** [comment] 2020-11-11 23:33
I had similar issue with 3.9. It is the networkx package had issues. just change `from fractions import gcd` to `from math import gcd` in the package should works for me.

The issue had been fixed in networkx master branch. Or you can overite use git+ in the requirements.txt

**Comment by sjoerdklaveringakpn** [comment] 2021-01-28 10:26
Can confirm this issues also occurs with Python 3.8.5, this is currently blocking me from update cfn-lint

`VersionConflict: (networkx 2.5 (c:\xxx\python38\lib\site-packages), Requirement.parse('networkx==2.1'))`

**Comment by zaro0508** [comment] 2021-04-23 19:01
networkx updated in PR #1008

**Closed by zaro0508** 2021-04-23 19:01 UTC
