### ISSUE TITLE
Support for networkx version 2.4

### ISSUE THREAD

**Issue by pipozzz** [Sceptre/sceptre#924] opened 2020-07-29 09:02 UTC
https://github.com/Sceptre/sceptre/blob/e28e0397bdc865646002bf3067ffee81ad8d1268/setup.py#L22

I think this should be able to support >=2.1  it instead of setting exact version here.

**Comment by zaro0508** [comment] 2020-07-29 14:14
duplicate of #916

**Closed by zaro0508** 2020-07-29 14:15 UTC
