### ISSUE TITLE
delete stack runs through all folder in path

### ISSUE THREAD

**Issue by annasaphira** [Sceptre/sceptre#1191] opened 2022-01-11 10:52 UTC
### Subject of the issue
Despite specifying a specific stack configuration to be deleted, the command checks the complete directory structure for completeness of the environment variable definition. This command aborts the deletion of the stack as soon as an environment variable is not defined in one of the existing stack configurations in the context of the pipeline job.

### Your environment
* sceptre2.7.1
* python 3.9.5-r2
* which Alpine 3.14.3

### Steps to reproduce
We have build following folder structure:
```
base_folder
│
└───config
│   │   config.yaml
│   │
│   └───eks
│   |   │   eks_dev.yaml
│   |   │   eks_tst.yaml
│   |   │   ...
│   |   
│   └───hostedzone
│       │   hostedzone_dev.yaml
│       │   hostedzone_tst.yaml
│       │   ...
│   
└───templates
    │   eks.yaml
    │   hostedzone.yaml
```
In config files we define environment variables. In configuration file hostedzone_dev.yaml is defined an evironment variable which is not in eks_dev.yaml. In both files we didn't have dependencies.

If we rollout the resources we use in different pipeline job following commands
``sceptre --dir ${CI_PROJECT_DIR}/<base_folder> launch /hostedzone/hostedzone_dev.yaml -y``
``sceptre --dir ${CI_PROJECT_DIR}/<base_folder> launch /eks/eks_dev.yaml -y``

If we delete only the eks resource we use:
``sceptre --dir ${CI_PROJECT_DIR}/<base_folder> delete /eks/<resource_name>_dev.yaml -y``

**out if we use option --debug**
``Traceback (most recent call last):
File "/usr/bin/sceptre", line 8, in <module>
sys.exit(cli())
File "/usr/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python3.9/site-packages/click/core.py", line 1053, in main
rv = self.invoke(ctx)
File "/usr/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python3.9/site-packages/click/core.py", line 754, in invoke
return __callback(*args, **kwargs)
File "/usr/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
return f(get_current_context(), *args, **kwargs)
File "/usr/lib/python3.9/site-packages/sceptre/cli/helpers.py", line 42, in decorated
return func(*args, **kwargs)
File "/usr/lib/python3.9/site-packages/sceptre/cli/delete.py", line 42, in delete_command
plan = SceptrePlan(context)
File "/usr/lib/python3.9/site-packages/sceptre/plan/plan.py", line 37, in __init__
all_stacks, command_stacks = config_reader.construct_stacks()
File "/usr/lib/python3.9/site-packages/sceptre/config/reader.py", line 234, in construct_stacks
stack = self._construct_stack(rel_path, stack_group_config)
File "/usr/lib/python3.9/site-packages/sceptre/config/reader.py", line 516, in _construct_stack
config = self.read(rel_path, stack_group_config)
File "/usr/lib/python3.9/site-packages/sceptre/config/reader.py", line 328, in read
this_config = self._recursive_read(directory_path, filename, config)
File "/usr/lib/python3.9/site-packages/sceptre/config/reader.py", line 373, in _recursive_read
child_config = self._render(directory_path, filename, config_group) or {}
File "/usr/lib/python3.9/site-packages/sceptre/config/reader.py", line 418, in _render
rendered_template = template.render(
File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
self.environment.handle_exception()
File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
reraise(*rewrite_traceback_stack(source=source))
File "/usr/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
raise value.with_traceback(tb)
File "/.../config/hosted-zone/hosted-zone-intern.yaml", line 7, in top-level template code
Extern: '{{ environment_variable.<UNKONOWN_VARIABLE_FROM_HOSTEDZONE_FILE> }}'
jinja2.exceptions.UndefinedError: 'os._Environ object' has no attribute '<UNKONOWN_VARIABLE_FROM_HOSTEDZONE_FILE>'``

### Expected behaviour
The command "scepter delete" checks only the specified file and delete stack.

### Actual behaviour
The command "scepter delete" checks all files in all subfolders for availability of the environment variables instead of only checking the specified stack configuration file and then dismantling the stack.

**Comment by zaro0508** [comment] 2022-01-11 17:17
have you tried using the `--ignore-dependencies` flag and would that ignore the other sceptre files?  for example ```sceptre --ignore-dependencies --dir ${CI_PROJECT_DIR}/<base_folder> delete /eks/<resource_name>_dev.yaml -y```

**Comment by EnricoBond** [comment] 2022-01-12 05:29
This will lead to the same error and this would be an other bug, because in the stack-configs are no dependencies declared.

**Comment by jfalkenstein** [comment] 2022-01-22 17:21
Hi @annasaphira , I understand what the issue is. It is the same thing as when you reference a `{{var.something}}` and that user variable isn't set.

Generally, this is very good behavior as it ensures that a Sceptre project is properly configured before it runs any stack actions, completely "compiling" the project. But in the case where you're trying to delete the stack and that environment variable is only used on the stack you're wanting to delete, I can imagine that's less than optimal behavior.

So here are a couple thoughts I have about this:

1. You could set a "default" on your environment variable, like `{{ environment_variable.MY_UNSET_VARIABLE | default("")}}` or `{{ environment_variable.get('MY_UNSET_VARIABLE') }}`. This will make the environment variable "optional" and won't fail when you attempt deletion. The downside here is that you might not want those envs to be optional under most circumstances.
2. You could use a user variable + jinja to disable the situation, something like this:

    ```yaml
    parameters:
        {% if not var.get('disable-envs') %}
        my_parameter: {{ environment_vairable.MY_UNSET_VARIABLE }}
        {% endif %}
    ```
    Doing this would allow you to pass `--var disable-envs=true` when invoking `sceptre delete` on it. 
3. You could just comment out that line temporarily. I know that's hacky, but deletion doesn't need it.

With all that said, this is one of the reasons I avoid using `{{ environment_variable.something }}` in my Stack Configs. My preference is generally using --var-file with a preconfigured set of variables for each environment, then using `--var` or (better yet) SSM parameters for more sensitive key/value pairs.

**Comment by EnricoBond** [comment] 2022-01-22 19:34
@jfalkenstein 

Thank you for your reply and also the possible solutions. I think we will go with the default values till this ist fixed. 

I say fixed because this behavior is only at delete. I would expect that "launch" and "delete" will work the same way. 
Launch works without problems even not all vars are set. 

So delete behaves differently as launch. 
And just to be sure all variables for the specific stack are set and the sceptre script will break because an independent variable of an other stack is missing.

**Comment by annasaphira** [comment] 2022-01-24 10:26
@jfalkenstein 

Thanks for your reply. My colleague has already answered for his use case and thus found an interim solution.

The container we are providing does not currently offer the option of using a variable file. We will work on this and check whether and how we can make the option available. 

However, like my colleague, I consider the option of not building all stacks at once and then deleting them again individually to be a basic function and look forward to a solution from Sceptre.

**Comment by craighurley** [comment] 2022-01-24 20:16
@jfalkenstein has provided sound advice.

> look forward to a solution from Sceptre.

Do you and your colleague/company offer time if the provided advice is not suitable?

**Comment by bswerdlen-godaddy** [comment] 2022-04-15 22:50
I am facing a similar issue. One of my unrelated stacks has a problem where an expected output can not be found and it is causing a dependency failure when trying to delete a specific piece of a functioning stack, even if I use '--ignore-dependencies'

The behavior I would expect is that '--ignore-dependencies' would completely skip the dependency check and just remove the stack I'm specifying with the delete.

My invocation and output:

sceptre --ignore-dependencies delete -y accountA/us-east-1/stackDir

Error:
accountB/us-east-1/appA/albA: Dependency accountB/us-east-1/appB/albB.yaml not found. Please make sure that your dependencies stack_outputs have their full path from `config` defined.

Is there anyway for force my way around this problem for the time being?

**Comment by jfalkenstein** [comment] 2022-07-22 15:27
This issue doesn't really identify a bug, per se, but rather some disagreement about how certain Sceptre functionality ought to operate. The issue name isn't really relevant to where this issue ended up. Since this issue isn't really targeted on a specific feature request or bug, I'm going to close it. @annasaphira if there _is_ a specific bug or feature request you'd like to make, I'd encourage you to open a new, more targeted issue.

**Closed by jfalkenstein** 2022-07-22 15:27 UTC
