### ISSUE TITLE
Could not connect to the endpoint URL

### ISSUE THREAD

**Issue by dlahn** [Sceptre/sceptre#891] opened 2020-04-01 12:44 UTC
When trying to run Sceptre, with a large amount of stacks, eventually, we run into: 

```
"Could not connect to the endpoint URL: \"https://cloudformation.eu-west-1.amazonaws.com/\""
```

Could this be retried? The odd thing is that when this occurs, it is not showing any rate limiting errors.

**Comment by ngfgrant** [comment] 2020-04-01 17:40
Hmm that’s a new one for me....

**Comment by dlahn** [comment] 2020-04-01 19:21
This seems to happen after quite some time of running, so I'm not sure if the CloudFormation API is just blocking me at some point. Immediately re-running works fine, but then again, the same issue. It would be great if Sceptre could catch this and retry.

**Comment by ngfgrant** [comment] 2020-04-01 20:58
Ok... I wonder if we could catch and step back the calls .... how big is your stack?

**Comment by dlahn** [comment] 2020-04-02 12:57
The stacks themselves are not very big... they are quite small, but when we do `sceptre launch`, it is running about 500 stacks.

**Comment by dlahn** [comment] 2020-05-01 15:25
Any idea how we can work around this? This is happening to us quite frequently.

**Comment by zaro0508** [comment] 2020-05-01 15:41
Which version of sceptre @dlahn?  and are you doing anything special via hooks or resolvers that make calls to AWS?

**Comment by dlahn** [comment] 2020-05-01 15:45
We are using the latest version (2.3.0). Mostly, nothing special. We have a few stack_output_external, but that's it. Most resolvers are just stack_output.

**Comment by ngfgrant** [comment] 2020-05-01 15:49
Not sure - I I do think we have a `retries` function somewhere but also I think that boto _might_ step back requests automatically. It is not a rate limit exceeded which is strange too....

**Comment by zaro0508** [comment] 2020-05-01 16:21
I've also seen this error in my scpetre logs as well but mine do finish because the sceptre backoff kicks in and retries.  Therefore I know that step back functionality in sceptre.  However there's no way for a user to override the the number of retries or the number of time between requests.  That might be something we may want to add @ngfgrant ?  

As a workaround for this this case I guess I would attempt to add in a sleep between stack groups or even between each template?  This can be done with a simple command hook, (i.e. `!cmd sleep 1`).

**Comment by zaro0508** [comment] 2021-12-05 00:47
closing because this issue is old and we cannot reproduce it.

**Closed by zaro0508** 2021-12-05 00:47 UTC
