### ISSUE TITLE
Launch command processes all environments instead of the passed in env

### ISSUE THREAD

**Issue by SpyderDave** [Sceptre/sceptre#913] opened 2020-06-26 19:55 UTC
Running sceptre 2.3.0 CLI

I have the following:

. 
- config
      -dev
          |- config.yaml
          |- devstack.yaml
      -qa
          |- config.yaml
          |- qastack.yaml
- templates
      devtemplate.yaml
      qatemplate.yaml

I want to launch the dev environment (which will eventually contain many stacks); 
    sceptre --yes launch dev

It seems to read in and process BOTH the dev and qa Stackgroups.

Since I have not completed the qa stuff yet, it's failing.

I want to understand what is wrong with the way I am running the CLI here.

**Comment by SpyderDave** [comment] 2020-06-26 20:03
#753

**Comment by zaro0508** [comment] 2020-07-28 01:20
I am using v2.3.0 as well but I don't have this problem @SpyderDave.  sceptre errors are a bit difficult to figure out because the error messages are not always clear.  I would suggest you try to reproduce with a simple and valid sceptre template in both dev and qa.  try running `sceptre launch dev --yes` then try running `sceptre launch qa --yes` again.

**Comment by ngfgrant** [comment] 2020-10-03 14:50
@SpyderDave did you manage to resolve your issue?

**Comment by SpyderDave** [comment] 2020-10-05 12:31
In my case, the only solution I found was to ensure the both stack sets were fully configured.  There seems to be a WIP to fix this issue but I dont know the status. If you follow #753 you will see lots of action on it.

**Comment by zaro0508** [comment] 2020-10-05 18:42
I think i read this issue incorrectly in the past.  Reading it again, I can confirm that this is a real issue.  I have this problem as well.  The root issue here is that Sceptre will load all files under the `config` folder even though you may only specify one of the folder (i.e. `launch config/dev`).  if there are unfinished sceptre files in `config/qa` folder it will process those and throw and error.  Thats seems ok, however the error message is not clear and doesn't specifically indicate which files had the errors.  

This could be two issues:
1. unclear error message, same as issue #897
2. sceptre should only load and process files specified by the launch command.

I think having clear error messages, fix num 1, would probably make people happy enough to not care about num 2?

**Comment by michal-sujkowski** [comment] 2021-05-21 12:43
I believe this could be fixed by this https://github.com/Sceptre/sceptre/issues/1042 issue with this https://github.com/Sceptre/sceptre/pull/1043 pr.

**Comment by zaro0508** [comment] 2021-06-23 16:17
thanks @michal-sujkowski I have verified that #1043 did indeed fix this issue.  Sceptre now only loads and process specified by the folder that's passed to the launch command.

**Closed by zaro0508** 2021-06-23 16:17 UTC
Labels: state: needs discussion, type: bug
