### ISSUE TITLE
How to reference the current StackName in the Config file

### ISSUE THREAD

**Issue by chrisduong** [Sceptre/sceptre#346] opened 2018-03-30 09:15 UTC
Hi,

I modular my Nested Cloudformation stack with Sceptre, so in my Config file, I need to get the current StackName for my Parameter. See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html#cfn-pseudo-param-stackname for all names.

Normally, within CFN, I can use `Ref: AWS::StackName`.

**Comment by et304383** [comment] 2018-04-24 18:09
I too would love this ability.  It's a bit of a pain having to construct the stack name in an environment or stack config when this value could be exposed to the templating abilities of the config files.

**Comment by zaro0508** [comment] 2022-02-05 17:36
duplicate of https://github.com/Sceptre/sceptre/discussions/1021

**Closed by zaro0508** 2022-02-05 17:36 UTC
Labels: type: feature request, state: needs discussion
