### ISSUE TITLE
Add support for Drift Detection

### ISSUE THREAD

**Issue by johnculkin** [Sceptre/sceptre#275] opened 2017-11-29 14:48 UTC
This is a lower priority and more for planning purposes.

Some details here:
https://stelligent.com/2017/11/28/new-for-cloudformation-in-2018-drift-detection/

**Comment by ngfgrant** [comment] 2018-02-16 15:37
Good suggestion. On hold until the feature is released by AWS.

**Comment by ryanpagel** [comment] 2018-04-03 18:30
Can't wait for this feature in AWS CloudFormation and Sceptre.

**Comment by pc-mreeves** [comment] 2018-07-05 17:04
Link is broken. Only reference I can find is here: https://aws.amazon.com/blogs/mt/aws-cloudformation-2017-in-review/

**Comment by jakul** [comment] 2018-11-14 09:18
Now released! https://aws.amazon.com/blogs/aws/new-cloudformation-drift-detection/

**Comment by zaro0508** [comment] 2021-12-05 01:17
duplicate of issue #1169 which contains a PR for drift detection feature.

**Closed by zaro0508** 2021-12-05 01:17 UTC
Labels: type: feature request, state: help wanted, priority: important
