### ISSUE TITLE
sceptre validate fails with obsolete stack config of which the template has already been deleted

### ISSUE THREAD

**Issue by mvanholsteijn** [Sceptre/sceptre#1491] opened 2024-07-31 14:44 UTC
### Subject of the issue
When running sceptre validate, the validate will fail on an obsolete stack config of which the template has already been deleted. 

### Your environment
* 4.4.2
* 3.9.11
* MacOS/Linux

### Steps to reproduce
- add an the property obsolete: true to a stack config
- delete the corresponding template file
- sceptre validate will error FileNotFoundError: [Errno 2] No such file or directory: 

### Expected behaviour
- that it either ignores the obsolete stack, ignores the error or that you can tell sceptre to ignore obsolete stack on validate (like launch --prune)

### Actual behaviour
-- sceptre validate errors with error FileNotFoundError: [Errno 2] No such file or directory:

**Comment by alexharv074** [comment] 2024-08-02 13:05
Much the same as with the other issue you have raised https://github.com/Sceptre/sceptre/issues/1492, my initial feeling is that this is working by design. Since the intent and purpose of `sceptre validate` is to _validate templates_, its use on stacks whose templates have been deleted does not make sense to me. 

I would be happy to offer advice on what I would do instead, but firstly you might have to explain why you would delete the template in the first place? Why is marking it as obsolete not sufficient? Apologies if this is a silly question, because I don't use this obsolete feature.

**Comment by zaro0508** [comment] 2024-08-02 14:32
@mvanholsteijn I would expect that sceptre validate should ignore sceptre configs that contain `obsolete:true`.  Do you know if this is a regression?  Does your sceptre config have [dependencies](https://docs.sceptre-project.org/latest/docs/stack_config.html#dependencies)?  Anyways, it would be very helpful if you can attach your scpetre config to this issue.

**Comment by alexharv074** [comment] 2024-08-03 01:07
@zaro0508  It does not appear to be a regression; I can reproduce the same behaviour using the commit where the feature was added, v3.2.0 and v3.2.2. The feature was added by @jfalkenstein and I wonder if he is around to offer any insights on whether this observed behaviour is a bug or intentional?

**Comment by alexharv074** [comment] 2024-08-04 01:33
@mvanholsteijn What is your reason for deleting the templates after marking stacks as `obsolete`? Although I have never used this feature, it would be my expectation that validate would fail if you deleted the template from a stack but left the config that referred to it behind. If you do not want the template any more, why would you want the config to be there? 

Again it could be my ignorance, as I have never used this feature.

**Comment by alexharv074** [comment] 2024-08-19 14:06
Having heard no response, closing this. I believe this is working as designed.

**Closed by alexharv074** 2024-08-19 14:06 UTC
