### ISSUE TITLE
Greedy pattern matching can cause ambiguity

### ISSUE THREAD

**Issue by jeffmacdonald** [Sceptre/sceptre#836] opened 2019-09-19 18:39 UTC
Lets say you have 2 config files rds.yaml and rds-vpc.yaml

Then lets say you have 4 other config files, each using stack_outputs from each other so they're all linked and one of them is linked to rds-vpc.yaml, thus creating a dependency chain.

If you run this `sceptre delete foo/boo/rds` , sceptre will greedy match rds-vpc.yaml and will ask you if you'd like to delete EVERYTHING. Which isn't great.

If you run `sceptre delete foo/boo/rds.yaml` it will of course only delete the rds stack, which did not have any dependencies.

Suggestion: Require full file path for stack config files and do not rely upon greedy pattern matching.

**Comment by craighurley** [comment] 2019-09-20 05:15
This should be fixed by https://github.com/Sceptre/sceptre/pull/731.  That PR needs a little love to push it across the line.

**Comment by ngfgrant** [comment] 2019-09-20 11:36
Thanks for raising @jeffmacdonald closing as it is a duplicate of https://github.com/Sceptre/sceptre/issues/546 and as @craighurley mentions will be resolved in #731

**Closed by ngfgrant** 2019-09-20 11:36 UTC

**Comment by jeffmacdonald** [comment] 2019-09-20 17:07
Sweet thanks! (it just bit me again in a new exciting way to this is great news :) )
