### ISSUE TITLE
Sceptre doesn't enumerate the list of resources in a text format

### ISSUE THREAD

**Issue by iliazlobin** [Sceptre/sceptre#949] opened 2020-10-18 14:40 UTC
When `sceptre list resources dev` command is launched after deploying a stack in [a getting started guide](https://sceptre.cloudreach.com/2.2.1/docs/get_started.html), the following error appears:
```
$ sceptre list resources dev
Traceback (most recent call last):
  File "/home/user/ws/godaddy/venv/bin/sceptre", line 8, in <module>
    sys.exit(cli())
  File "/home/user/ws/godaddy/venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/ws/godaddy/venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/ws/godaddy/venv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/ws/godaddy/venv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/ws/godaddy/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/ws/godaddy/venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/ws/godaddy/venv/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/ws/godaddy/venv/lib/python3.6/site-packages/sceptre/cli/helpers.py", line 36, in decorated
    return func(*args, **kwargs)
  File "/home/user/ws/godaddy/venv/lib/python3.6/site-packages/sceptre/cli/list.py", line 47, in list_resources
    write(responses, context.output_format)
  File "/home/user/ws/godaddy/venv/lib/python3.6/site-packages/sceptre/cli/helpers.py", line 80, in write
    output = "---\n".join(var)
TypeError: sequence item 0: expected str instance, dict found
```

The problem has to do with [trying to represent a complex dict type in a plain string by joining the result of nested maps](https://github.com/Sceptre/sceptre/blob/v2.4.0/sceptre/cli/helpers.py#L78-L80), which is not supported by python.

![image](https://user-images.githubusercontent.com/3456942/96371086-bcfe8580-1168-11eb-8933-f5112e7cc061.png)

**Workaround**
Specify `--output` argument to format the result:
```
$ sceptre --output yaml list resources dev
---
- dev/vpc:
  - LogicalResourceId: VPC
    PhysicalResourceId: vpc-06de1c64677936e34
```

**Comment by zaro0508** [comment] 2020-10-18 19:33
duplicate of issue #881 fix for it is in PR #918

**Closed by zaro0508** 2020-10-18 19:33 UTC
