### ISSUE TITLE
`stack_tags` does not support !resolvers

### ISSUE THREAD

**Issue by mattvonrocketstein** [Sceptre/sceptre#426] opened 2018-07-05 18:40 UTC
I have a custom resolver that tags my stacks with repo name/git hash, but using that I end up with cloudformation stack tags like `<resolver object>`.

**Comment by brent-johnson** [comment] 2020-07-09 22:51
I learned of this issue today because I wanted to use a custom resolver for tagging and obviously it did not work.

**Comment by zaro0508** [comment] 2021-12-05 01:23
duplicate of issue #1114

**Closed by zaro0508** 2021-12-05 01:23 UTC
